export const clients_dummy_data: Client[] = [
  {
    active: true,
    date_joined: new Date(),
    email: 'client@mailnator.com',
    name: 'Samuel Adeniyi',
    wallet_balance: 20100,
  },
  {
    active: false,
    date_joined: new Date(),
    email: 'client@mailnator.com',
    name: 'Samuel Adeniyi',
    wallet_balance: 20100,
  },
  {
    active: false,
    date_joined: new Date(),
    email: 'client@mailnator.com',
    name: 'Samuel Adeniyi',
    wallet_balance: 20100,
  },
  {
    active: true,
    date_joined: new Date(),
    email: 'client@mailnator.com',
    name: 'Samuel Adeniyi',
    wallet_balance: 20100,
  },
  {
    active: true,
    date_joined: new Date(),
    email: 'client@mailnator.com',
    name: 'Samuel Adeniyi',
    wallet_balance: 20100,
  },
  {
    active: true,
    date_joined: new Date(),
    email: 'client@mailnator.com',
    name: 'Samuel Adeniyi',
    wallet_balance: 20100,
  },
  {
    active: false,
    date_joined: new Date(),
    email: 'client@mailnator.com',
    name: 'Samuel Adeniyi',
    wallet_balance: 20100,
  },
  {
    active: false,
    date_joined: new Date(),
    email: 'client@mailnator.com',
    name: 'Samuel Adeniyi',
    wallet_balance: 20100,
  },
  {
    active: false,
    date_joined: new Date(),
    email: 'client@mailnator.com',
    name: 'Samuel Adeniyi',
    wallet_balance: 20100,
  },
  {
    active: true,
    date_joined: new Date(),
    email: 'client@mailnator.com',
    name: 'Samuel Adeniyi',
    wallet_balance: 20100,
  },
  {
    active: false,
    date_joined: new Date(),
    email: 'client@mailnator.com',
    name: 'Samuel Adeniyi',
    wallet_balance: 20100,
  },
];
